/* 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/


exports.generateFibonacci = (maxValue) => {
    var fibonacciArray = [1, 2];
    var i = 2;
    while (fibonacciArray[fibonacciArray.length - 1] <= maxValue) {
        fibonacciArray.push(fibonacciArray[i - 2] + fibonacciArray[i - 1]);
        i++
    }
    fibonacciArray.pop();
    return fibonacciArray.filter(
        (newValue) => newValue % 2 == 0
    ).reduce((previusValue, newValue) => previusValue + newValue, 0)
}